// packages/react-shared/src/components/Button.tsx
import React from "react"
import ReactDOM from "react-dom/client"

export function Button() {
  const [counter, setCounter] = React.useState(0)
  return (
    <div
      onClick={() => setCounter(counter + 1)}
      className="w-60 h-16 rounded bg-yellow-400 text-slate-900 dark:bg-rose-500 dark:text-white cursor-pointer select-none flex items-center justify-center"
    >
      <span className="text-xl font-bold">React Button: {counter}</span>
    </div>
  )
}

export default function RenderElement(el: HTMLDivElement) {
  const root = ReactDOM.createRoot(el)

  root.render(
    <React.StrictMode>
      <Button />
    </React.StrictMode>
  )
}

// packages/vue-shared/src/components/Button.vue
<template>
  <div
    @click="counter++"
    class="w-60 h-16 rounded bg-sky-400 text-white dark:bg-lime-500 dark:text-black cursor-pointer select-none flex items-center justify-center"
  >
    <span className="text-xl font-bold">Vue Button: {{ counter }}</span>
  </div>
</template>

<script setup lang="ts">
import { ref, createApp } from "vue"

const counter = ref(0)
</script>
